#! /usr/bin/env bash

set -ex

: ${MADX_VERSION:=5.05.02}
: ${CPYMAD_VERSION:=1.4.2}
: ${PY:=/opt/python/cp36-cp36m/bin}

# Build MAD-X
if [[ $(cat /io/install/version) != $MADX_VERSION ]]; then
    rm -rf /io/install
    mkdir -p /io/install
    echo $MADX_VERSION > /io/install/version

    if [[ -f $MADX_ARCHIVE ]]; then
        tar -xzf $MADX_ARCHIVE --one-top-level=/io/MAD-X --strip-components 1
    elif [[ ! -e /io/MAD-X ]]; then
        git clone git://github.com/MethodicalAcceleratorDesign/MAD-X /io/MAD-X
        git -C /io/MAD-X checkout $MADX_VERSION

        # Patch an incompatibility with cmake28 in recent MAD-X (my fault). We
        # can drop this once migrating to manylinux 2019 (with newer cmake):
        patch -d /io/MAD-X -p1 < "$here"/cmake28_hotfix.patch
    fi

    mkdir -p /io/build/madx
    cd /io/build/madx
    cmake28 /io/MAD-X \
        -DBUILD_SHARED_LIBS=OFF \
        -DMADX_STATIC=ON \
        -DCMAKE_INSTALL_PREFIX=/io/install \
        -DCMAKE_C_FLAGS="-fvisibility=hidden" \
        -DMADX_INSTALL_DOC=OFF \
        -DMADX_ONLINE=OFF \
        -DMADX_FORCE_32=OFF \
        -DMADX_X11=OFF
    make install
fi

# Download cpymad:
if [[ ! -f $CPYMAD_ARCHIVE ]]; then
    if [[ ! -e /io/cpymad ]]; then
        git clone git://github.com/hibtc/cpymad /io/cpymad
        git -C /io/cpymad checkout $CPYMAD_VERSION
    fi

    # The cpymad folder may be mounted from the host OS. For this reason we
    # should not create root owned files there or modify any of the user's data.
    # For this reason, we first copy the source files to a build folder and
    # perform all further steps from there:
    cd /io/cpymad
    rm -rf /io/build/cpymad
    mkdir -p /io/build/cpymad
    $PY/python setup.py egg_info
    tar -c $(cat src/cpymad.egg-info/SOURCES.txt) |
        tar -x -C /io/build/cpymad --no-same-owner

    # We create the wheels from the source distribution to verify that the
    # source distribution can be used as installation medium. We will later
    # upload this exact source distribution to PyPI:
    cd /io/build/cpymad
    $PY/pip install cython
    $PY/python setup.py sdist
    $PY/pip uninstall cython -y

    CPYMAD_ARCHIVE="$(ls /io/build/cpymad/dist/*.tar.gz)"
fi

export X11=0 BLAS=0 LAPACK=0 MADXDIR=/io/install
for PYBIN in /opt/python/*/bin; do
    "${PYBIN}/pip" install -U setuptools
    "${PYBIN}/pip" wheel "$CPYMAD_ARCHIVE" --no-deps -w /io/build/cpymad/dist/
done

# Bundle external shared libraries into the wheels
mkdir -p /io/dist
for whl in /io/build/cpymad/dist/*.whl; do
    auditwheel repair "$whl" -w /io/dist
done
cp "$CPYMAD_ARCHIVE" /io/dist
